import type { Project } from '@/types'

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'demo01',
    name: 'Aurora Chat',
    url: 'https://aurora-chat.example.com',
    description: '极光风格的多模型聊天前端，支持流式输出与分支对话。',
    category: 'AI',
    icon: '✨',
    accentColor: '#c084fc',
    pinned: true,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 12,
    visits: 142,
  },
  {
    id: 'demo02',
    name: 'zai2api',
    url: 'https://zai2api.workers.dev',
    description: 'Z.ai API 代理，Cloudflare Workers + D1，复古书卷风后台。',
    category: '工具',
    icon: '🛠️',
    accentColor: '#22d3ee',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    visits: 87,
  },
  {
    id: 'demo03',
    name: '沉浸扮演 Demo',
    url: 'https://roleplay.example.app',
    description: '动态调色板 + 玻璃态聊天泡泡，移动端沉浸式角色扮演。',
    category: '实验',
    icon: '🎭',
    accentColor: '#f472b6',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    visits: 56,
  },
  {
    id: 'demo04',
    name: '生成台 Studio',
    url: 'https://create.example.app',
    description: 'Next.js 创作台，左侧会话栏 + 中央对话流 + 右侧自动滚动图片墙。',
    category: 'AI',
    icon: '🎨',
    accentColor: '#34d399',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    visits: 23,
  },
  {
    id: 'demo05',
    name: 'OCR 实验',
    url: 'https://ocr.zeabur.app',
    description: '截图转结构化清单的小服务，识别精度对比测评。',
    category: '实验',
    icon: '👁️',
    accentColor: '#818cf8',
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
    visits: 11,
  },
  {
    id: 'demo06',
    name: '导航站本体',
    url: 'https://nav.example.dev',
    description: '你正在看的这个页面 — 玻璃 + 极光 + 实时存活检测。',
    category: '工具',
    icon: '🌌',
    accentColor: '#a78bfa',
    createdAt: Date.now(),
    visits: 0,
  },
]
